// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: background_jobs.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const createBackgroundJob = `-- name: CreateBackgroundJob :one
INSERT INTO background_jobs (
    session_id,
    origin,
    command,
    description,
    working_dir,
    started_at,
    instance_id,
    log_pre_publish_lost
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING id
`

type CreateBackgroundJobParams struct {
	SessionID         string `json:"session_id"`
	Origin            string `json:"origin"`
	Command           string `json:"command"`
	Description       string `json:"description"`
	WorkingDir        string `json:"working_dir"`
	StartedAt         int64  `json:"started_at"`
	InstanceID        string `json:"instance_id"`
	LogPrePublishLost int64  `json:"log_pre_publish_lost"`
}

func (q *Queries) CreateBackgroundJob(ctx context.Context, arg CreateBackgroundJobParams) (int64, error) {
	row := q.queryRow(ctx, q.createBackgroundJobStmt, createBackgroundJob,
		arg.SessionID,
		arg.Origin,
		arg.Command,
		arg.Description,
		arg.WorkingDir,
		arg.StartedAt,
		arg.InstanceID,
		arg.LogPrePublishLost,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteAnvilInstance = `-- name: DeleteAnvilInstance :exec
DELETE FROM anvil_instances
WHERE id = ?
`

func (q *Queries) DeleteAnvilInstance(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteAnvilInstanceStmt, deleteAnvilInstance, id)
	return err
}

const deleteBackgroundJob = `-- name: DeleteBackgroundJob :exec
DELETE FROM background_jobs
WHERE id = ?
`

func (q *Queries) DeleteBackgroundJob(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteBackgroundJobStmt, deleteBackgroundJob, id)
	return err
}

const deleteBackgroundJobsBySession = `-- name: DeleteBackgroundJobsBySession :exec
DELETE FROM background_jobs
WHERE session_id = ?
`

func (q *Queries) DeleteBackgroundJobsBySession(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.deleteBackgroundJobsBySessionStmt, deleteBackgroundJobsBySession, sessionID)
	return err
}

const finalizeBackgroundJob = `-- name: FinalizeBackgroundJob :execrows
UPDATE background_jobs
SET
    completed_at = ?,
    exit_code = ?,
    end_reason = ?,
    log_bytes = ?,
    log_truncated = ?,
    log_write_error = ?
WHERE id = ? AND completed_at IS NULL
`

type FinalizeBackgroundJobParams struct {
	CompletedAt   sql.NullInt64  `json:"completed_at"`
	ExitCode      sql.NullInt64  `json:"exit_code"`
	EndReason     sql.NullString `json:"end_reason"`
	LogBytes      int64          `json:"log_bytes"`
	LogTruncated  int64          `json:"log_truncated"`
	LogWriteError string         `json:"log_write_error"`
	ID            int64          `json:"id"`
}

func (q *Queries) FinalizeBackgroundJob(ctx context.Context, arg FinalizeBackgroundJobParams) (int64, error) {
	result, err := q.exec(ctx, q.finalizeBackgroundJobStmt, finalizeBackgroundJob,
		arg.CompletedAt,
		arg.ExitCode,
		arg.EndReason,
		arg.LogBytes,
		arg.LogTruncated,
		arg.LogWriteError,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBackgroundJob = `-- name: GetBackgroundJob :one
SELECT id, session_id, origin, command, description, working_dir, started_at, completed_at, exit_code, end_reason, instance_id, log_bytes, log_truncated, log_pre_publish_lost, log_write_error, log_expired_at
FROM background_jobs
WHERE id = ? LIMIT 1
`

func (q *Queries) GetBackgroundJob(ctx context.Context, id int64) (BackgroundJob, error) {
	row := q.queryRow(ctx, q.getBackgroundJobStmt, getBackgroundJob, id)
	var i BackgroundJob
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Origin,
		&i.Command,
		&i.Description,
		&i.WorkingDir,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ExitCode,
		&i.EndReason,
		&i.InstanceID,
		&i.LogBytes,
		&i.LogTruncated,
		&i.LogPrePublishLost,
		&i.LogWriteError,
		&i.LogExpiredAt,
	)
	return i, err
}

const listAnvilInstances = `-- name: ListAnvilInstances :many
SELECT id, pid, started_at, heartbeat_at
FROM anvil_instances
ORDER BY id ASC
`

func (q *Queries) ListAnvilInstances(ctx context.Context) ([]AnvilInstance, error) {
	rows, err := q.query(ctx, q.listAnvilInstancesStmt, listAnvilInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnvilInstance{}
	for rows.Next() {
		var i AnvilInstance
		if err := rows.Scan(
			&i.ID,
			&i.Pid,
			&i.StartedAt,
			&i.HeartbeatAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackgroundJobIDsBySession = `-- name: ListBackgroundJobIDsBySession :many
SELECT id
FROM background_jobs
WHERE session_id = ?
ORDER BY id ASC
`

func (q *Queries) ListBackgroundJobIDsBySession(ctx context.Context, sessionID string) ([]int64, error) {
	rows, err := q.query(ctx, q.listBackgroundJobIDsBySessionStmt, listBackgroundJobIDsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackgroundJobLogsOldestFirst = `-- name: ListBackgroundJobLogsOldestFirst :many
SELECT id, log_bytes
FROM background_jobs
WHERE completed_at IS NOT NULL
  AND log_expired_at IS NULL
ORDER BY completed_at ASC, id ASC
`

type ListBackgroundJobLogsOldestFirstRow struct {
	ID       int64 `json:"id"`
	LogBytes int64 `json:"log_bytes"`
}

func (q *Queries) ListBackgroundJobLogsOldestFirst(ctx context.Context) ([]ListBackgroundJobLogsOldestFirstRow, error) {
	rows, err := q.query(ctx, q.listBackgroundJobLogsOldestFirstStmt, listBackgroundJobLogsOldestFirst)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackgroundJobLogsOldestFirstRow{}
	for rows.Next() {
		var i ListBackgroundJobLogsOldestFirstRow
		if err := rows.Scan(&i.ID, &i.LogBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackgroundJobsBySession = `-- name: ListBackgroundJobsBySession :many
SELECT id, session_id, origin, command, description, working_dir, started_at, completed_at, exit_code, end_reason, instance_id, log_bytes, log_truncated, log_pre_publish_lost, log_write_error, log_expired_at
FROM background_jobs
WHERE session_id = ?
ORDER BY id ASC
`

func (q *Queries) ListBackgroundJobsBySession(ctx context.Context, sessionID string) ([]BackgroundJob, error) {
	rows, err := q.query(ctx, q.listBackgroundJobsBySessionStmt, listBackgroundJobsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackgroundJob{}
	for rows.Next() {
		var i BackgroundJob
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Origin,
			&i.Command,
			&i.Description,
			&i.WorkingDir,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ExitCode,
			&i.EndReason,
			&i.InstanceID,
			&i.LogBytes,
			&i.LogTruncated,
			&i.LogPrePublishLost,
			&i.LogWriteError,
			&i.LogExpiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackgroundJobsWithLogsBefore = `-- name: ListBackgroundJobsWithLogsBefore :many
SELECT id, session_id, origin, command, description, working_dir, started_at, completed_at, exit_code, end_reason, instance_id, log_bytes, log_truncated, log_pre_publish_lost, log_write_error, log_expired_at
FROM background_jobs
WHERE completed_at IS NOT NULL
  AND completed_at < ?
  AND log_expired_at IS NULL
ORDER BY completed_at ASC, id ASC
`

func (q *Queries) ListBackgroundJobsWithLogsBefore(ctx context.Context, completedAt sql.NullInt64) ([]BackgroundJob, error) {
	rows, err := q.query(ctx, q.listBackgroundJobsWithLogsBeforeStmt, listBackgroundJobsWithLogsBefore, completedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackgroundJob{}
	for rows.Next() {
		var i BackgroundJob
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Origin,
			&i.Command,
			&i.Description,
			&i.WorkingDir,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ExitCode,
			&i.EndReason,
			&i.InstanceID,
			&i.LogBytes,
			&i.LogTruncated,
			&i.LogPrePublishLost,
			&i.LogWriteError,
			&i.LogExpiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningBackgroundJobs = `-- name: ListRunningBackgroundJobs :many
SELECT id, session_id, origin, command, description, working_dir, started_at, completed_at, exit_code, end_reason, instance_id, log_bytes, log_truncated, log_pre_publish_lost, log_write_error, log_expired_at
FROM background_jobs
WHERE completed_at IS NULL
ORDER BY id ASC
`

func (q *Queries) ListRunningBackgroundJobs(ctx context.Context) ([]BackgroundJob, error) {
	rows, err := q.query(ctx, q.listRunningBackgroundJobsStmt, listRunningBackgroundJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackgroundJob{}
	for rows.Next() {
		var i BackgroundJob
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Origin,
			&i.Command,
			&i.Description,
			&i.WorkingDir,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ExitCode,
			&i.EndReason,
			&i.InstanceID,
			&i.LogBytes,
			&i.LogTruncated,
			&i.LogPrePublishLost,
			&i.LogWriteError,
			&i.LogExpiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBackgroundJobLogExpired = `-- name: MarkBackgroundJobLogExpired :exec
UPDATE background_jobs
SET log_expired_at = ?
WHERE id = ?
`

type MarkBackgroundJobLogExpiredParams struct {
	LogExpiredAt sql.NullInt64 `json:"log_expired_at"`
	ID           int64         `json:"id"`
}

func (q *Queries) MarkBackgroundJobLogExpired(ctx context.Context, arg MarkBackgroundJobLogExpiredParams) error {
	_, err := q.exec(ctx, q.markBackgroundJobLogExpiredStmt, markBackgroundJobLogExpired, arg.LogExpiredAt, arg.ID)
	return err
}

const markBackgroundJobsInterrupted = `-- name: MarkBackgroundJobsInterrupted :exec
UPDATE background_jobs
SET
    completed_at = ?,
    end_reason = 'interrupted'
WHERE instance_id = ? AND completed_at IS NULL
`

type MarkBackgroundJobsInterruptedParams struct {
	CompletedAt sql.NullInt64 `json:"completed_at"`
	InstanceID  string        `json:"instance_id"`
}

func (q *Queries) MarkBackgroundJobsInterrupted(ctx context.Context, arg MarkBackgroundJobsInterruptedParams) error {
	_, err := q.exec(ctx, q.markBackgroundJobsInterruptedStmt, markBackgroundJobsInterrupted, arg.CompletedAt, arg.InstanceID)
	return err
}

const touchAnvilInstance = `-- name: TouchAnvilInstance :exec
UPDATE anvil_instances
SET heartbeat_at = ?
WHERE id = ?
`

type TouchAnvilInstanceParams struct {
	HeartbeatAt int64  `json:"heartbeat_at"`
	ID          string `json:"id"`
}

func (q *Queries) TouchAnvilInstance(ctx context.Context, arg TouchAnvilInstanceParams) error {
	_, err := q.exec(ctx, q.touchAnvilInstanceStmt, touchAnvilInstance, arg.HeartbeatAt, arg.ID)
	return err
}

const transferBackgroundJobs = `-- name: TransferBackgroundJobs :exec
UPDATE background_jobs
SET session_id = ?1
WHERE id IN (/*SLICE:ids*/?)
`

type TransferBackgroundJobsParams struct {
	SessionID string  `json:"session_id"`
	Ids       []int64 `json:"ids"`
}

func (q *Queries) TransferBackgroundJobs(ctx context.Context, arg TransferBackgroundJobsParams) error {
	query := transferBackgroundJobs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.SessionID)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.exec(ctx, nil, query, queryParams...)
	return err
}

const upsertAnvilInstance = `-- name: UpsertAnvilInstance :exec
INSERT INTO anvil_instances (
    id,
    pid,
    started_at,
    heartbeat_at
) VALUES (
    ?, ?, ?, ?
)
ON CONFLICT (id) DO UPDATE SET
    pid = excluded.pid,
    started_at = excluded.started_at,
    heartbeat_at = excluded.heartbeat_at
`

type UpsertAnvilInstanceParams struct {
	ID          string `json:"id"`
	Pid         int64  `json:"pid"`
	StartedAt   int64  `json:"started_at"`
	HeartbeatAt int64  `json:"heartbeat_at"`
}

func (q *Queries) UpsertAnvilInstance(ctx context.Context, arg UpsertAnvilInstanceParams) error {
	_, err := q.exec(ctx, q.upsertAnvilInstanceStmt, upsertAnvilInstance,
		arg.ID,
		arg.Pid,
		arg.StartedAt,
		arg.HeartbeatAt,
	)
	return err
}
