// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: background_job_events.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const claimBackgroundJobEvents = `-- name: ClaimBackgroundJobEvents :many
UPDATE background_job_events
SET
    state = 'claimed',
    claimed_by = ?1,
    claimed_at = ?2
WHERE id IN (/*SLICE:ids*/?)
  AND (state = 'pending' OR (state = 'claimed' AND claimed_by = ?1))
RETURNING id
`

type ClaimBackgroundJobEventsParams struct {
	ClaimedBy string        `json:"claimed_by"`
	ClaimedAt sql.NullInt64 `json:"claimed_at"`
	Ids       []string      `json:"ids"`
}

func (q *Queries) ClaimBackgroundJobEvents(ctx context.Context, arg ClaimBackgroundJobEventsParams) ([]string, error) {
	query := claimBackgroundJobEvents
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ClaimedBy)
	queryParams = append(queryParams, arg.ClaimedAt)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createBackgroundJobEvent = `-- name: CreateBackgroundJobEvent :exec
INSERT INTO background_job_events (
    id,
    job_id,
    kind,
    watch_gen,
    line,
    tail,
    state,
    created_at
) VALUES (
    ?, ?, ?, ?, ?, ?, 'pending', ?
)
`

type CreateBackgroundJobEventParams struct {
	ID        string `json:"id"`
	JobID     int64  `json:"job_id"`
	Kind      string `json:"kind"`
	WatchGen  int64  `json:"watch_gen"`
	Line      string `json:"line"`
	Tail      string `json:"tail"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) CreateBackgroundJobEvent(ctx context.Context, arg CreateBackgroundJobEventParams) error {
	_, err := q.exec(ctx, q.createBackgroundJobEventStmt, createBackgroundJobEvent,
		arg.ID,
		arg.JobID,
		arg.Kind,
		arg.WatchGen,
		arg.Line,
		arg.Tail,
		arg.CreatedAt,
	)
	return err
}

const deleteBackgroundJobEvent = `-- name: DeleteBackgroundJobEvent :exec
DELETE FROM background_job_events
WHERE id = ?
`

func (q *Queries) DeleteBackgroundJobEvent(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteBackgroundJobEventStmt, deleteBackgroundJobEvent, id)
	return err
}

const listUndeliveredBackgroundJobEvents = `-- name: ListUndeliveredBackgroundJobEvents :many
SELECT
    e.id,
    e.job_id,
    e.kind,
    e.watch_gen,
    e.line,
    e.tail,
    e.state,
    e.claimed_by,
    e.created_at,
    j.session_id,
    j.origin,
    j.command,
    j.description,
    j.working_dir,
    j.started_at,
    j.completed_at,
    j.exit_code
FROM background_job_events e
JOIN background_jobs j ON j.id = e.job_id
ORDER BY e.created_at ASC, e.id ASC
`

type ListUndeliveredBackgroundJobEventsRow struct {
	ID          string        `json:"id"`
	JobID       int64         `json:"job_id"`
	Kind        string        `json:"kind"`
	WatchGen    int64         `json:"watch_gen"`
	Line        string        `json:"line"`
	Tail        string        `json:"tail"`
	State       string        `json:"state"`
	ClaimedBy   string        `json:"claimed_by"`
	CreatedAt   int64         `json:"created_at"`
	SessionID   string        `json:"session_id"`
	Origin      string        `json:"origin"`
	Command     string        `json:"command"`
	Description string        `json:"description"`
	WorkingDir  string        `json:"working_dir"`
	StartedAt   int64         `json:"started_at"`
	CompletedAt sql.NullInt64 `json:"completed_at"`
	ExitCode    sql.NullInt64 `json:"exit_code"`
}

func (q *Queries) ListUndeliveredBackgroundJobEvents(ctx context.Context) ([]ListUndeliveredBackgroundJobEventsRow, error) {
	rows, err := q.query(ctx, q.listUndeliveredBackgroundJobEventsStmt, listUndeliveredBackgroundJobEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUndeliveredBackgroundJobEventsRow{}
	for rows.Next() {
		var i ListUndeliveredBackgroundJobEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Kind,
			&i.WatchGen,
			&i.Line,
			&i.Tail,
			&i.State,
			&i.ClaimedBy,
			&i.CreatedAt,
			&i.SessionID,
			&i.Origin,
			&i.Command,
			&i.Description,
			&i.WorkingDir,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ExitCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseBackgroundJobEvent = `-- name: ReleaseBackgroundJobEvent :exec
UPDATE background_job_events
SET
    state = 'pending',
    claimed_by = '',
    claimed_at = NULL
WHERE id = ?
`

func (q *Queries) ReleaseBackgroundJobEvent(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.releaseBackgroundJobEventStmt, releaseBackgroundJobEvent, id)
	return err
}
