// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createMessageStmt, err = db.PrepareContext(ctx, createMessage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMessage: %w", err)
	}
	if q.createSessionStmt, err = db.PrepareContext(ctx, createSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSession: %w", err)
	}
	if q.deleteMCPOAuthClientStmt, err = db.PrepareContext(ctx, deleteMCPOAuthClient); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMCPOAuthClient: %w", err)
	}
	if q.deleteMCPOAuthTokenStmt, err = db.PrepareContext(ctx, deleteMCPOAuthToken); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMCPOAuthToken: %w", err)
	}
	if q.deleteMessageStmt, err = db.PrepareContext(ctx, deleteMessage); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMessage: %w", err)
	}
	if q.deleteSessionStmt, err = db.PrepareContext(ctx, deleteSession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSession: %w", err)
	}
	if q.deleteSessionMessagesStmt, err = db.PrepareContext(ctx, deleteSessionMessages); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionMessages: %w", err)
	}
	if q.getAllSessionMessagesStmt, err = db.PrepareContext(ctx, getAllSessionMessages); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllSessionMessages: %w", err)
	}
	if q.getBranchPathStmt, err = db.PrepareContext(ctx, getBranchPath); err != nil {
		return nil, fmt.Errorf("error preparing query GetBranchPath: %w", err)
	}
	if q.getBranchPathTailStmt, err = db.PrepareContext(ctx, getBranchPathTail); err != nil {
		return nil, fmt.Errorf("error preparing query GetBranchPathTail: %w", err)
	}
	if q.getFileReadStmt, err = db.PrepareContext(ctx, getFileRead); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileRead: %w", err)
	}
	if q.getLastGlobalSessionStmt, err = db.PrepareContext(ctx, getLastGlobalSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetLastGlobalSession: %w", err)
	}
	if q.getLastSessionByWorkingDirStmt, err = db.PrepareContext(ctx, getLastSessionByWorkingDir); err != nil {
		return nil, fmt.Errorf("error preparing query GetLastSessionByWorkingDir: %w", err)
	}
	if q.getMCPOAuthClientStmt, err = db.PrepareContext(ctx, getMCPOAuthClient); err != nil {
		return nil, fmt.Errorf("error preparing query GetMCPOAuthClient: %w", err)
	}
	if q.getMCPOAuthTokenStmt, err = db.PrepareContext(ctx, getMCPOAuthToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetMCPOAuthToken: %w", err)
	}
	if q.getMessageStmt, err = db.PrepareContext(ctx, getMessage); err != nil {
		return nil, fmt.Errorf("error preparing query GetMessage: %w", err)
	}
	if q.getMessageChildrenStmt, err = db.PrepareContext(ctx, getMessageChildren); err != nil {
		return nil, fmt.Errorf("error preparing query GetMessageChildren: %w", err)
	}
	if q.getSessionByIDStmt, err = db.PrepareContext(ctx, getSessionByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionByID: %w", err)
	}
	if q.listAllSessionsStmt, err = db.PrepareContext(ctx, listAllSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllSessions: %w", err)
	}
	if q.listMessagesBySessionStmt, err = db.PrepareContext(ctx, listMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListMessagesBySession: %w", err)
	}
	if q.listPinnedSessionsStmt, err = db.PrepareContext(ctx, listPinnedSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListPinnedSessions: %w", err)
	}
	if q.listSessionReadFilesStmt, err = db.PrepareContext(ctx, listSessionReadFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionReadFiles: %w", err)
	}
	if q.listSessionsByWorkingDirStmt, err = db.PrepareContext(ctx, listSessionsByWorkingDir); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionsByWorkingDir: %w", err)
	}
	if q.listUserMessagesBySessionStmt, err = db.PrepareContext(ctx, listUserMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListUserMessagesBySession: %w", err)
	}
	if q.listUserMessagesByWorkingDirStmt, err = db.PrepareContext(ctx, listUserMessagesByWorkingDir); err != nil {
		return nil, fmt.Errorf("error preparing query ListUserMessagesByWorkingDir: %w", err)
	}
	if q.recordFileReadStmt, err = db.PrepareContext(ctx, recordFileRead); err != nil {
		return nil, fmt.Errorf("error preparing query RecordFileRead: %w", err)
	}
	if q.renameSessionStmt, err = db.PrepareContext(ctx, renameSession); err != nil {
		return nil, fmt.Errorf("error preparing query RenameSession: %w", err)
	}
	if q.setSessionPinStmt, err = db.PrepareContext(ctx, setSessionPin); err != nil {
		return nil, fmt.Errorf("error preparing query SetSessionPin: %w", err)
	}
	if q.updateMessageStmt, err = db.PrepareContext(ctx, updateMessage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMessage: %w", err)
	}
	if q.updateSessionStmt, err = db.PrepareContext(ctx, updateSession); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSession: %w", err)
	}
	if q.updateSessionLeafStmt, err = db.PrepareContext(ctx, updateSessionLeaf); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSessionLeaf: %w", err)
	}
	if q.updateSessionTitleAndUsageStmt, err = db.PrepareContext(ctx, updateSessionTitleAndUsage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSessionTitleAndUsage: %w", err)
	}
	if q.upsertMCPOAuthClientStmt, err = db.PrepareContext(ctx, upsertMCPOAuthClient); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertMCPOAuthClient: %w", err)
	}
	if q.upsertMCPOAuthTokenStmt, err = db.PrepareContext(ctx, upsertMCPOAuthToken); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertMCPOAuthToken: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createMessageStmt != nil {
		if cerr := q.createMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMessageStmt: %w", cerr)
		}
	}
	if q.createSessionStmt != nil {
		if cerr := q.createSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionStmt: %w", cerr)
		}
	}
	if q.deleteMCPOAuthClientStmt != nil {
		if cerr := q.deleteMCPOAuthClientStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMCPOAuthClientStmt: %w", cerr)
		}
	}
	if q.deleteMCPOAuthTokenStmt != nil {
		if cerr := q.deleteMCPOAuthTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMCPOAuthTokenStmt: %w", cerr)
		}
	}
	if q.deleteMessageStmt != nil {
		if cerr := q.deleteMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMessageStmt: %w", cerr)
		}
	}
	if q.deleteSessionStmt != nil {
		if cerr := q.deleteSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionStmt: %w", cerr)
		}
	}
	if q.deleteSessionMessagesStmt != nil {
		if cerr := q.deleteSessionMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionMessagesStmt: %w", cerr)
		}
	}
	if q.getAllSessionMessagesStmt != nil {
		if cerr := q.getAllSessionMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllSessionMessagesStmt: %w", cerr)
		}
	}
	if q.getBranchPathStmt != nil {
		if cerr := q.getBranchPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBranchPathStmt: %w", cerr)
		}
	}
	if q.getBranchPathTailStmt != nil {
		if cerr := q.getBranchPathTailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBranchPathTailStmt: %w", cerr)
		}
	}
	if q.getFileReadStmt != nil {
		if cerr := q.getFileReadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileReadStmt: %w", cerr)
		}
	}
	if q.getLastGlobalSessionStmt != nil {
		if cerr := q.getLastGlobalSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLastGlobalSessionStmt: %w", cerr)
		}
	}
	if q.getLastSessionByWorkingDirStmt != nil {
		if cerr := q.getLastSessionByWorkingDirStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLastSessionByWorkingDirStmt: %w", cerr)
		}
	}
	if q.getMCPOAuthClientStmt != nil {
		if cerr := q.getMCPOAuthClientStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMCPOAuthClientStmt: %w", cerr)
		}
	}
	if q.getMCPOAuthTokenStmt != nil {
		if cerr := q.getMCPOAuthTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMCPOAuthTokenStmt: %w", cerr)
		}
	}
	if q.getMessageStmt != nil {
		if cerr := q.getMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMessageStmt: %w", cerr)
		}
	}
	if q.getMessageChildrenStmt != nil {
		if cerr := q.getMessageChildrenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMessageChildrenStmt: %w", cerr)
		}
	}
	if q.getSessionByIDStmt != nil {
		if cerr := q.getSessionByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionByIDStmt: %w", cerr)
		}
	}
	if q.listAllSessionsStmt != nil {
		if cerr := q.listAllSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllSessionsStmt: %w", cerr)
		}
	}
	if q.listMessagesBySessionStmt != nil {
		if cerr := q.listMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.listPinnedSessionsStmt != nil {
		if cerr := q.listPinnedSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPinnedSessionsStmt: %w", cerr)
		}
	}
	if q.listSessionReadFilesStmt != nil {
		if cerr := q.listSessionReadFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionReadFilesStmt: %w", cerr)
		}
	}
	if q.listSessionsByWorkingDirStmt != nil {
		if cerr := q.listSessionsByWorkingDirStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsByWorkingDirStmt: %w", cerr)
		}
	}
	if q.listUserMessagesBySessionStmt != nil {
		if cerr := q.listUserMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUserMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.listUserMessagesByWorkingDirStmt != nil {
		if cerr := q.listUserMessagesByWorkingDirStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUserMessagesByWorkingDirStmt: %w", cerr)
		}
	}
	if q.recordFileReadStmt != nil {
		if cerr := q.recordFileReadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing recordFileReadStmt: %w", cerr)
		}
	}
	if q.renameSessionStmt != nil {
		if cerr := q.renameSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing renameSessionStmt: %w", cerr)
		}
	}
	if q.setSessionPinStmt != nil {
		if cerr := q.setSessionPinStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setSessionPinStmt: %w", cerr)
		}
	}
	if q.updateMessageStmt != nil {
		if cerr := q.updateMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMessageStmt: %w", cerr)
		}
	}
	if q.updateSessionStmt != nil {
		if cerr := q.updateSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionStmt: %w", cerr)
		}
	}
	if q.updateSessionLeafStmt != nil {
		if cerr := q.updateSessionLeafStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionLeafStmt: %w", cerr)
		}
	}
	if q.updateSessionTitleAndUsageStmt != nil {
		if cerr := q.updateSessionTitleAndUsageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionTitleAndUsageStmt: %w", cerr)
		}
	}
	if q.upsertMCPOAuthClientStmt != nil {
		if cerr := q.upsertMCPOAuthClientStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertMCPOAuthClientStmt: %w", cerr)
		}
	}
	if q.upsertMCPOAuthTokenStmt != nil {
		if cerr := q.upsertMCPOAuthTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertMCPOAuthTokenStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                               DBTX
	tx                               *sql.Tx
	createMessageStmt                *sql.Stmt
	createSessionStmt                *sql.Stmt
	deleteMCPOAuthClientStmt         *sql.Stmt
	deleteMCPOAuthTokenStmt          *sql.Stmt
	deleteMessageStmt                *sql.Stmt
	deleteSessionStmt                *sql.Stmt
	deleteSessionMessagesStmt        *sql.Stmt
	getAllSessionMessagesStmt        *sql.Stmt
	getBranchPathStmt                *sql.Stmt
	getBranchPathTailStmt            *sql.Stmt
	getFileReadStmt                  *sql.Stmt
	getLastGlobalSessionStmt         *sql.Stmt
	getLastSessionByWorkingDirStmt   *sql.Stmt
	getMCPOAuthClientStmt            *sql.Stmt
	getMCPOAuthTokenStmt             *sql.Stmt
	getMessageStmt                   *sql.Stmt
	getMessageChildrenStmt           *sql.Stmt
	getSessionByIDStmt               *sql.Stmt
	listAllSessionsStmt              *sql.Stmt
	listMessagesBySessionStmt        *sql.Stmt
	listPinnedSessionsStmt           *sql.Stmt
	listSessionReadFilesStmt         *sql.Stmt
	listSessionsByWorkingDirStmt     *sql.Stmt
	listUserMessagesBySessionStmt    *sql.Stmt
	listUserMessagesByWorkingDirStmt *sql.Stmt
	recordFileReadStmt               *sql.Stmt
	renameSessionStmt                *sql.Stmt
	setSessionPinStmt                *sql.Stmt
	updateMessageStmt                *sql.Stmt
	updateSessionStmt                *sql.Stmt
	updateSessionLeafStmt            *sql.Stmt
	updateSessionTitleAndUsageStmt   *sql.Stmt
	upsertMCPOAuthClientStmt         *sql.Stmt
	upsertMCPOAuthTokenStmt          *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                               tx,
		tx:                               tx,
		createMessageStmt:                q.createMessageStmt,
		createSessionStmt:                q.createSessionStmt,
		deleteMCPOAuthClientStmt:         q.deleteMCPOAuthClientStmt,
		deleteMCPOAuthTokenStmt:          q.deleteMCPOAuthTokenStmt,
		deleteMessageStmt:                q.deleteMessageStmt,
		deleteSessionStmt:                q.deleteSessionStmt,
		deleteSessionMessagesStmt:        q.deleteSessionMessagesStmt,
		getAllSessionMessagesStmt:        q.getAllSessionMessagesStmt,
		getBranchPathStmt:                q.getBranchPathStmt,
		getBranchPathTailStmt:            q.getBranchPathTailStmt,
		getFileReadStmt:                  q.getFileReadStmt,
		getLastGlobalSessionStmt:         q.getLastGlobalSessionStmt,
		getLastSessionByWorkingDirStmt:   q.getLastSessionByWorkingDirStmt,
		getMCPOAuthClientStmt:            q.getMCPOAuthClientStmt,
		getMCPOAuthTokenStmt:             q.getMCPOAuthTokenStmt,
		getMessageStmt:                   q.getMessageStmt,
		getMessageChildrenStmt:           q.getMessageChildrenStmt,
		getSessionByIDStmt:               q.getSessionByIDStmt,
		listAllSessionsStmt:              q.listAllSessionsStmt,
		listMessagesBySessionStmt:        q.listMessagesBySessionStmt,
		listPinnedSessionsStmt:           q.listPinnedSessionsStmt,
		listSessionReadFilesStmt:         q.listSessionReadFilesStmt,
		listSessionsByWorkingDirStmt:     q.listSessionsByWorkingDirStmt,
		listUserMessagesBySessionStmt:    q.listUserMessagesBySessionStmt,
		listUserMessagesByWorkingDirStmt: q.listUserMessagesByWorkingDirStmt,
		recordFileReadStmt:               q.recordFileReadStmt,
		renameSessionStmt:                q.renameSessionStmt,
		setSessionPinStmt:                q.setSessionPinStmt,
		updateMessageStmt:                q.updateMessageStmt,
		updateSessionStmt:                q.updateSessionStmt,
		updateSessionLeafStmt:            q.updateSessionLeafStmt,
		updateSessionTitleAndUsageStmt:   q.updateSessionTitleAndUsageStmt,
		upsertMCPOAuthClientStmt:         q.upsertMCPOAuthClientStmt,
		upsertMCPOAuthTokenStmt:          q.upsertMCPOAuthTokenStmt,
	}
}
