// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mcp_oauth.sql

package db

import (
	"context"
	"database/sql"
)

const deleteMCPOAuthClient = `-- name: DeleteMCPOAuthClient :exec
DELETE FROM mcp_oauth_clients WHERE server_name = ?
`

func (q *Queries) DeleteMCPOAuthClient(ctx context.Context, serverName string) error {
	_, err := q.exec(ctx, q.deleteMCPOAuthClientStmt, deleteMCPOAuthClient, serverName)
	return err
}

const deleteMCPOAuthToken = `-- name: DeleteMCPOAuthToken :exec
DELETE FROM mcp_oauth_tokens WHERE server_name = ?
`

func (q *Queries) DeleteMCPOAuthToken(ctx context.Context, serverName string) error {
	_, err := q.exec(ctx, q.deleteMCPOAuthTokenStmt, deleteMCPOAuthToken, serverName)
	return err
}

const getMCPOAuthClient = `-- name: GetMCPOAuthClient :one
SELECT server_name, server_url, client_id, client_secret, created_at FROM mcp_oauth_clients WHERE server_name = ?
`

func (q *Queries) GetMCPOAuthClient(ctx context.Context, serverName string) (McpOauthClient, error) {
	row := q.queryRow(ctx, q.getMCPOAuthClientStmt, getMCPOAuthClient, serverName)
	var i McpOauthClient
	err := row.Scan(
		&i.ServerName,
		&i.ServerUrl,
		&i.ClientID,
		&i.ClientSecret,
		&i.CreatedAt,
	)
	return i, err
}

const getMCPOAuthToken = `-- name: GetMCPOAuthToken :one
SELECT server_name, server_url, access_token, refresh_token, token_type, expiry, scopes, token_endpoint, client_id, client_secret, created_at, updated_at FROM mcp_oauth_tokens WHERE server_name = ?
`

func (q *Queries) GetMCPOAuthToken(ctx context.Context, serverName string) (McpOauthToken, error) {
	row := q.queryRow(ctx, q.getMCPOAuthTokenStmt, getMCPOAuthToken, serverName)
	var i McpOauthToken
	err := row.Scan(
		&i.ServerName,
		&i.ServerUrl,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenType,
		&i.Expiry,
		&i.Scopes,
		&i.TokenEndpoint,
		&i.ClientID,
		&i.ClientSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMCPOAuthClient = `-- name: UpsertMCPOAuthClient :exec
INSERT INTO mcp_oauth_clients (
    server_name, server_url, client_id, client_secret
) VALUES (?, ?, ?, ?)
ON CONFLICT(server_name) DO UPDATE SET
    server_url = excluded.server_url,
    client_id = excluded.client_id,
    client_secret = excluded.client_secret
`

type UpsertMCPOAuthClientParams struct {
	ServerName   string         `json:"server_name"`
	ServerUrl    string         `json:"server_url"`
	ClientID     string         `json:"client_id"`
	ClientSecret sql.NullString `json:"client_secret"`
}

func (q *Queries) UpsertMCPOAuthClient(ctx context.Context, arg UpsertMCPOAuthClientParams) error {
	_, err := q.exec(ctx, q.upsertMCPOAuthClientStmt, upsertMCPOAuthClient,
		arg.ServerName,
		arg.ServerUrl,
		arg.ClientID,
		arg.ClientSecret,
	)
	return err
}

const upsertMCPOAuthToken = `-- name: UpsertMCPOAuthToken :exec
INSERT INTO mcp_oauth_tokens (
    server_name, server_url, access_token, refresh_token,
    token_type, expiry, scopes, token_endpoint, client_id,
    client_secret, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, strftime('%s', 'now'))
ON CONFLICT(server_name) DO UPDATE SET
    server_url = excluded.server_url,
    access_token = excluded.access_token,
    refresh_token = excluded.refresh_token,
    token_type = excluded.token_type,
    expiry = excluded.expiry,
    scopes = excluded.scopes,
    token_endpoint = excluded.token_endpoint,
    client_id = excluded.client_id,
    client_secret = excluded.client_secret,
    updated_at = strftime('%s', 'now')
`

type UpsertMCPOAuthTokenParams struct {
	ServerName    string         `json:"server_name"`
	ServerUrl     string         `json:"server_url"`
	AccessToken   string         `json:"access_token"`
	RefreshToken  sql.NullString `json:"refresh_token"`
	TokenType     string         `json:"token_type"`
	Expiry        sql.NullInt64  `json:"expiry"`
	Scopes        sql.NullString `json:"scopes"`
	TokenEndpoint sql.NullString `json:"token_endpoint"`
	ClientID      string         `json:"client_id"`
	ClientSecret  sql.NullString `json:"client_secret"`
}

func (q *Queries) UpsertMCPOAuthToken(ctx context.Context, arg UpsertMCPOAuthTokenParams) error {
	_, err := q.exec(ctx, q.upsertMCPOAuthTokenStmt, upsertMCPOAuthToken,
		arg.ServerName,
		arg.ServerUrl,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenType,
		arg.Expiry,
		arg.Scopes,
		arg.TokenEndpoint,
		arg.ClientID,
		arg.ClientSecret,
	)
	return err
}
