// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"
	"database/sql"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    id,
    session_id,
    role,
    parts,
    model,
    provider,
    parent_message_id,
    message_type,
    created_at,
    updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, strftime('%s', 'now'), strftime('%s', 'now')
)
RETURNING id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, parent_message_id, message_type
`

type CreateMessageParams struct {
	ID              string         `json:"id"`
	SessionID       string         `json:"session_id"`
	Role            string         `json:"role"`
	Parts           string         `json:"parts"`
	Model           sql.NullString `json:"model"`
	Provider        sql.NullString `json:"provider"`
	ParentMessageID sql.NullString `json:"parent_message_id"`
	MessageType     string         `json:"message_type"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.queryRow(ctx, q.createMessageStmt, createMessage,
		arg.ID,
		arg.SessionID,
		arg.Role,
		arg.Parts,
		arg.Model,
		arg.Provider,
		arg.ParentMessageID,
		arg.MessageType,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Parts,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.Provider,
		&i.ParentMessageID,
		&i.MessageType,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages
WHERE id = ?
`

func (q *Queries) DeleteMessage(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteMessageStmt, deleteMessage, id)
	return err
}

const deleteSessionMessages = `-- name: DeleteSessionMessages :exec
DELETE FROM messages
WHERE session_id = ?
`

func (q *Queries) DeleteSessionMessages(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.deleteSessionMessagesStmt, deleteSessionMessages, sessionID)
	return err
}

const getAllSessionMessages = `-- name: GetAllSessionMessages :many
SELECT id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, parent_message_id, message_type
FROM messages
WHERE session_id = ?1
ORDER BY created_at ASC, rowid ASC
`

func (q *Queries) GetAllSessionMessages(ctx context.Context, sessionID string) ([]Message, error) {
	rows, err := q.query(ctx, q.getAllSessionMessagesStmt, getAllSessionMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.Provider,
			&i.ParentMessageID,
			&i.MessageType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBranchPath = `-- name: GetBranchPath :many
WITH RECURSIVE branch AS (
    SELECT m.id, m.session_id, m.role, m.parts, m.model, m.created_at, m.updated_at,
           m.finished_at, m.provider, m.parent_message_id, m.message_type,
           0 AS depth
    FROM messages m WHERE m.id = ?1
    UNION ALL
    SELECT p.id, p.session_id, p.role, p.parts, p.model, p.created_at, p.updated_at,
           p.finished_at, p.provider, p.parent_message_id, p.message_type,
           b.depth + 1
    FROM messages p JOIN branch b ON p.id = b.parent_message_id
    WHERE b.depth < 10000
)
SELECT id, session_id, role, parts, model, created_at, updated_at, finished_at,
       provider, parent_message_id, message_type
FROM branch ORDER BY depth DESC
`

type GetBranchPathRow struct {
	ID              string         `json:"id"`
	SessionID       string         `json:"session_id"`
	Role            string         `json:"role"`
	Parts           string         `json:"parts"`
	Model           sql.NullString `json:"model"`
	CreatedAt       int64          `json:"created_at"`
	UpdatedAt       int64          `json:"updated_at"`
	FinishedAt      sql.NullInt64  `json:"finished_at"`
	Provider        sql.NullString `json:"provider"`
	ParentMessageID sql.NullString `json:"parent_message_id"`
	MessageType     string         `json:"message_type"`
}

func (q *Queries) GetBranchPath(ctx context.Context, leafID string) ([]GetBranchPathRow, error) {
	rows, err := q.query(ctx, q.getBranchPathStmt, getBranchPath, leafID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBranchPathRow{}
	for rows.Next() {
		var i GetBranchPathRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.Provider,
			&i.ParentMessageID,
			&i.MessageType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBranchPathTail = `-- name: GetBranchPathTail :many
WITH RECURSIVE branch AS (
    SELECT m.id, m.session_id, m.role, m.parts, m.model, m.created_at, m.updated_at,
           m.finished_at, m.provider, m.parent_message_id, m.message_type,
           0 AS depth
    FROM messages m WHERE m.id = ?1
    UNION ALL
    SELECT p.id, p.session_id, p.role, p.parts, p.model, p.created_at, p.updated_at,
           p.finished_at, p.provider, p.parent_message_id, p.message_type,
           b.depth + 1
    FROM messages p JOIN branch b ON p.id = b.parent_message_id
    WHERE b.depth + 1 < CAST(?2 AS INTEGER)
)
SELECT id, session_id, role, parts, model, created_at, updated_at, finished_at,
       provider, parent_message_id, message_type
FROM branch ORDER BY depth DESC
`

type GetBranchPathTailParams struct {
	LeafID   string `json:"leaf_id"`
	MaxDepth int64  `json:"max_depth"`
}

type GetBranchPathTailRow struct {
	ID              string         `json:"id"`
	SessionID       string         `json:"session_id"`
	Role            string         `json:"role"`
	Parts           string         `json:"parts"`
	Model           sql.NullString `json:"model"`
	CreatedAt       int64          `json:"created_at"`
	UpdatedAt       int64          `json:"updated_at"`
	FinishedAt      sql.NullInt64  `json:"finished_at"`
	Provider        sql.NullString `json:"provider"`
	ParentMessageID sql.NullString `json:"parent_message_id"`
	MessageType     string         `json:"message_type"`
}

func (q *Queries) GetBranchPathTail(ctx context.Context, arg GetBranchPathTailParams) ([]GetBranchPathTailRow, error) {
	rows, err := q.query(ctx, q.getBranchPathTailStmt, getBranchPathTail, arg.LeafID, arg.MaxDepth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBranchPathTailRow{}
	for rows.Next() {
		var i GetBranchPathTailRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.Provider,
			&i.ParentMessageID,
			&i.MessageType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessage = `-- name: GetMessage :one
SELECT id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, parent_message_id, message_type
FROM messages
WHERE id = ? LIMIT 1
`

func (q *Queries) GetMessage(ctx context.Context, id string) (Message, error) {
	row := q.queryRow(ctx, q.getMessageStmt, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Parts,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.Provider,
		&i.ParentMessageID,
		&i.MessageType,
	)
	return i, err
}

const getMessageChildren = `-- name: GetMessageChildren :many
SELECT id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, parent_message_id, message_type
FROM messages
WHERE parent_message_id = ?1
ORDER BY created_at ASC
`

func (q *Queries) GetMessageChildren(ctx context.Context, parentID sql.NullString) ([]Message, error) {
	rows, err := q.query(ctx, q.getMessageChildrenStmt, getMessageChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.Provider,
			&i.ParentMessageID,
			&i.MessageType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBySession = `-- name: ListMessagesBySession :many
SELECT id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, parent_message_id, message_type
FROM messages
WHERE session_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error) {
	rows, err := q.query(ctx, q.listMessagesBySessionStmt, listMessagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.Provider,
			&i.ParentMessageID,
			&i.MessageType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMessagesBySession = `-- name: ListUserMessagesBySession :many
SELECT id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, parent_message_id, message_type
FROM messages
WHERE session_id = ? AND role = 'user'
ORDER BY created_at DESC
`

func (q *Queries) ListUserMessagesBySession(ctx context.Context, sessionID string) ([]Message, error) {
	rows, err := q.query(ctx, q.listUserMessagesBySessionStmt, listUserMessagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.Provider,
			&i.ParentMessageID,
			&i.MessageType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMessagesByWorkingDir = `-- name: ListUserMessagesByWorkingDir :many
SELECT m.id, m.session_id, m.role, m.parts, m.model, m.created_at, m.updated_at, m.finished_at, m.provider, m.parent_message_id, m.message_type
FROM messages m
JOIN sessions s ON m.session_id = s.id
WHERE m.role = 'user' AND s.working_dir = ?
ORDER BY m.created_at DESC
`

func (q *Queries) ListUserMessagesByWorkingDir(ctx context.Context, workingDir string) ([]Message, error) {
	rows, err := q.query(ctx, q.listUserMessagesByWorkingDirStmt, listUserMessagesByWorkingDir, workingDir)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.Provider,
			&i.ParentMessageID,
			&i.MessageType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessage = `-- name: UpdateMessage :exec
UPDATE messages
SET
    parts = ?,
    finished_at = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateMessageParams struct {
	Parts      string        `json:"parts"`
	FinishedAt sql.NullInt64 `json:"finished_at"`
	ID         string        `json:"id"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) error {
	_, err := q.exec(ctx, q.updateMessageStmt, updateMessage, arg.Parts, arg.FinishedAt, arg.ID)
	return err
}
