// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type File struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	Content   string `json:"content"`
	Version   int64  `json:"version"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type McpOauthClient struct {
	ServerName   string         `json:"server_name"`
	ServerUrl    string         `json:"server_url"`
	ClientID     string         `json:"client_id"`
	ClientSecret sql.NullString `json:"client_secret"`
	CreatedAt    int64          `json:"created_at"`
}

type McpOauthToken struct {
	ServerName    string         `json:"server_name"`
	ServerUrl     string         `json:"server_url"`
	AccessToken   string         `json:"access_token"`
	RefreshToken  sql.NullString `json:"refresh_token"`
	TokenType     string         `json:"token_type"`
	Expiry        sql.NullInt64  `json:"expiry"`
	Scopes        sql.NullString `json:"scopes"`
	TokenEndpoint sql.NullString `json:"token_endpoint"`
	ClientID      string         `json:"client_id"`
	ClientSecret  sql.NullString `json:"client_secret"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
}

type Message struct {
	ID              string         `json:"id"`
	SessionID       string         `json:"session_id"`
	Role            string         `json:"role"`
	Parts           string         `json:"parts"`
	Model           sql.NullString `json:"model"`
	CreatedAt       int64          `json:"created_at"`
	UpdatedAt       int64          `json:"updated_at"`
	FinishedAt      sql.NullInt64  `json:"finished_at"`
	Provider        sql.NullString `json:"provider"`
	ParentMessageID sql.NullString `json:"parent_message_id"`
	MessageType     string         `json:"message_type"`
}

type MigrationsCompleted struct {
	SourcePath string `json:"source_path"`
	MigratedAt int64  `json:"migrated_at"`
}

type ReadFile struct {
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	ReadAt    int64  `json:"read_at"`
}

type Session struct {
	ID               string         `json:"id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	Title            string         `json:"title"`
	MessageCount     int64          `json:"message_count"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	Cost             float64        `json:"cost"`
	UpdatedAt        int64          `json:"updated_at"`
	CreatedAt        int64          `json:"created_at"`
	Todos            sql.NullString `json:"todos"`
	LeafMessageID    sql.NullString `json:"leaf_message_id"`
	WorkingDir       string         `json:"working_dir"`
}
