// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type AnvilInstance struct {
	ID          string `json:"id"`
	Pid         int64  `json:"pid"`
	StartedAt   int64  `json:"started_at"`
	HeartbeatAt int64  `json:"heartbeat_at"`
}

type BackgroundJob struct {
	ID                int64          `json:"id"`
	SessionID         string         `json:"session_id"`
	Origin            string         `json:"origin"`
	Command           string         `json:"command"`
	Description       string         `json:"description"`
	WorkingDir        string         `json:"working_dir"`
	StartedAt         int64          `json:"started_at"`
	CompletedAt       sql.NullInt64  `json:"completed_at"`
	ExitCode          sql.NullInt64  `json:"exit_code"`
	EndReason         sql.NullString `json:"end_reason"`
	InstanceID        string         `json:"instance_id"`
	LogBytes          int64          `json:"log_bytes"`
	LogTruncated      int64          `json:"log_truncated"`
	LogPrePublishLost int64          `json:"log_pre_publish_lost"`
	LogWriteError     string         `json:"log_write_error"`
	LogExpiredAt      sql.NullInt64  `json:"log_expired_at"`
}

type BackgroundJobEvent struct {
	ID        string        `json:"id"`
	JobID     int64         `json:"job_id"`
	Kind      string        `json:"kind"`
	WatchGen  int64         `json:"watch_gen"`
	Line      string        `json:"line"`
	Tail      string        `json:"tail"`
	State     string        `json:"state"`
	ClaimedBy string        `json:"claimed_by"`
	ClaimedAt sql.NullInt64 `json:"claimed_at"`
	CreatedAt int64         `json:"created_at"`
}

type McpOauthClient struct {
	ServerName   string         `json:"server_name"`
	ServerUrl    string         `json:"server_url"`
	ClientID     string         `json:"client_id"`
	ClientSecret sql.NullString `json:"client_secret"`
	CreatedAt    int64          `json:"created_at"`
}

type McpOauthToken struct {
	ServerName    string         `json:"server_name"`
	ServerUrl     string         `json:"server_url"`
	AccessToken   string         `json:"access_token"`
	RefreshToken  sql.NullString `json:"refresh_token"`
	TokenType     string         `json:"token_type"`
	Expiry        sql.NullInt64  `json:"expiry"`
	Scopes        sql.NullString `json:"scopes"`
	TokenEndpoint sql.NullString `json:"token_endpoint"`
	ClientID      string         `json:"client_id"`
	ClientSecret  sql.NullString `json:"client_secret"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
}

type Message struct {
	ID              string         `json:"id"`
	SessionID       string         `json:"session_id"`
	Role            string         `json:"role"`
	Parts           string         `json:"parts"`
	Model           sql.NullString `json:"model"`
	CreatedAt       int64          `json:"created_at"`
	UpdatedAt       int64          `json:"updated_at"`
	FinishedAt      sql.NullInt64  `json:"finished_at"`
	Provider        sql.NullString `json:"provider"`
	ParentMessageID sql.NullString `json:"parent_message_id"`
	MessageType     string         `json:"message_type"`
}

type MigrationsCompleted struct {
	SourcePath string `json:"source_path"`
	MigratedAt int64  `json:"migrated_at"`
}

type PermissionDecision struct {
	ID            string         `json:"id"`
	SessionID     string         `json:"session_id"`
	ToolCallID    string         `json:"tool_call_id"`
	ToolName      string         `json:"tool_name"`
	Action        string         `json:"action"`
	Input         string         `json:"input"`
	InputSegments string         `json:"input_segments"`
	WorkingDir    string         `json:"working_dir"`
	DecidedBy     string         `json:"decided_by"`
	Verdict       string         `json:"verdict"`
	MatchedRule   string         `json:"matched_rule"`
	Assessment    sql.NullString `json:"assessment"`
	CreatedAt     int64          `json:"created_at"`
}

type ReadFile struct {
	SessionID   string `json:"session_id"`
	Path        string `json:"path"`
	ReadAt      int64  `json:"read_at"`
	ContentHash string `json:"content_hash"`
}

type Session struct {
	ID               string         `json:"id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	Title            string         `json:"title"`
	MessageCount     int64          `json:"message_count"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	Cost             float64        `json:"cost"`
	UpdatedAt        int64          `json:"updated_at"`
	CreatedAt        int64          `json:"created_at"`
	Todos            sql.NullString `json:"todos"`
	LeafMessageID    sql.NullString `json:"leaf_message_id"`
	WorkingDir       string         `json:"working_dir"`
	TitleIsCustom    int64          `json:"title_is_custom"`
	Pinned           int64          `json:"pinned"`
	PinNote          string         `json:"pin_note"`
}

type StepUsage struct {
	ID                 string        `json:"id"`
	SessionID          string        `json:"session_id"`
	ParentSessionID    string        `json:"parent_session_id"`
	WorkingDir         string        `json:"working_dir"`
	MessageID          string        `json:"message_id"`
	Agent              string        `json:"agent"`
	Kind               string        `json:"kind"`
	Depth              int64         `json:"depth"`
	RunID              string        `json:"run_id"`
	StepIndex          int64         `json:"step_index"`
	Attempt            int64         `json:"attempt"`
	Provider           string        `json:"provider"`
	ProviderType       string        `json:"provider_type"`
	Model              string        `json:"model"`
	RequestStartedAt   int64         `json:"request_started_at"`
	ResponseFinishedAt int64         `json:"response_finished_at"`
	RetryCount         int64         `json:"retry_count"`
	FinishReason       string        `json:"finish_reason"`
	InputTokens        int64         `json:"input_tokens"`
	CacheReadTokens    int64         `json:"cache_read_tokens"`
	CacheWriteTokens   int64         `json:"cache_write_tokens"`
	OutputTokens       int64         `json:"output_tokens"`
	ReasoningTokens    int64         `json:"reasoning_tokens"`
	Estimated          int64         `json:"estimated"`
	RawUsage           string        `json:"raw_usage"`
	PriceInput         float64       `json:"price_input"`
	PriceOutput        float64       `json:"price_output"`
	PriceCacheRead     float64       `json:"price_cache_read"`
	PriceCacheWrite    float64       `json:"price_cache_write"`
	FlatRate           int64         `json:"flat_rate"`
	CachePolicy        string        `json:"cache_policy"`
	MessageCount       int64         `json:"message_count"`
	SystemCount        int64         `json:"system_count"`
	ToolCount          int64         `json:"tool_count"`
	ToolsHash          string        `json:"tools_hash"`
	SystemHash         string        `json:"system_hash"`
	HistoryHash        string        `json:"history_hash"`
	HistoryPrefixMatch sql.NullInt64 `json:"history_prefix_match"`
	FingerprintError   string        `json:"fingerprint_error"`
}
