// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permission_decisions.sql

package db

import (
	"context"
	"database/sql"
)

const countUnresolvedPermissionDecisionsSince = `-- name: CountUnresolvedPermissionDecisionsSince :one
SELECT COUNT(*) FROM permission_decisions
WHERE created_at >= ?
AND decided_by IN ('human', 'assessor', 'session_grant', 'session_rule')
`

func (q *Queries) CountUnresolvedPermissionDecisionsSince(ctx context.Context, createdAt int64) (int64, error) {
	row := q.queryRow(ctx, q.countUnresolvedPermissionDecisionsSinceStmt, countUnresolvedPermissionDecisionsSince, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePermissionDecisionsBefore = `-- name: DeletePermissionDecisionsBefore :exec
DELETE FROM permission_decisions WHERE created_at < ?
`

func (q *Queries) DeletePermissionDecisionsBefore(ctx context.Context, createdAt int64) error {
	_, err := q.exec(ctx, q.deletePermissionDecisionsBeforeStmt, deletePermissionDecisionsBefore, createdAt)
	return err
}

const insertPermissionDecision = `-- name: InsertPermissionDecision :exec
INSERT INTO permission_decisions (
    id, session_id, tool_call_id, tool_name, action, input,
    input_segments, working_dir, decided_by, verdict, matched_rule,
    assessment, created_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, strftime('%s', 'now')
)
`

type InsertPermissionDecisionParams struct {
	ID            string         `json:"id"`
	SessionID     string         `json:"session_id"`
	ToolCallID    string         `json:"tool_call_id"`
	ToolName      string         `json:"tool_name"`
	Action        string         `json:"action"`
	Input         string         `json:"input"`
	InputSegments string         `json:"input_segments"`
	WorkingDir    string         `json:"working_dir"`
	DecidedBy     string         `json:"decided_by"`
	Verdict       string         `json:"verdict"`
	MatchedRule   string         `json:"matched_rule"`
	Assessment    sql.NullString `json:"assessment"`
}

func (q *Queries) InsertPermissionDecision(ctx context.Context, arg InsertPermissionDecisionParams) error {
	_, err := q.exec(ctx, q.insertPermissionDecisionStmt, insertPermissionDecision,
		arg.ID,
		arg.SessionID,
		arg.ToolCallID,
		arg.ToolName,
		arg.Action,
		arg.Input,
		arg.InputSegments,
		arg.WorkingDir,
		arg.DecidedBy,
		arg.Verdict,
		arg.MatchedRule,
		arg.Assessment,
	)
	return err
}

const listPermissionDecisionsSince = `-- name: ListPermissionDecisionsSince :many
SELECT id, session_id, tool_call_id, tool_name, "action", input, input_segments, working_dir, decided_by, verdict, matched_rule, assessment, created_at FROM permission_decisions
WHERE created_at >= ?
ORDER BY created_at ASC
`

func (q *Queries) ListPermissionDecisionsSince(ctx context.Context, createdAt int64) ([]PermissionDecision, error) {
	rows, err := q.query(ctx, q.listPermissionDecisionsSinceStmt, listPermissionDecisionsSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PermissionDecision{}
	for rows.Next() {
		var i PermissionDecision
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ToolCallID,
			&i.ToolName,
			&i.Action,
			&i.Input,
			&i.InputSegments,
			&i.WorkingDir,
			&i.DecidedBy,
			&i.Verdict,
			&i.MatchedRule,
			&i.Assessment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
