// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteFile(ctx context.Context, id string) error
	DeleteMCPOAuthClient(ctx context.Context, serverName string) error
	DeleteMCPOAuthToken(ctx context.Context, serverName string) error
	DeleteMessage(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionFiles(ctx context.Context, sessionID string) error
	DeleteSessionMessages(ctx context.Context, sessionID string) error
	GetAllSessionMessages(ctx context.Context, sessionID string) ([]Message, error)
	GetBranchPath(ctx context.Context, leafID string) ([]GetBranchPathRow, error)
	GetBranchPathTail(ctx context.Context, arg GetBranchPathTailParams) ([]GetBranchPathTailRow, error)
	GetFile(ctx context.Context, id string) (File, error)
	GetFileByPathAndSession(ctx context.Context, arg GetFileByPathAndSessionParams) (File, error)
	GetFileRead(ctx context.Context, arg GetFileReadParams) (ReadFile, error)
	GetLastGlobalSession(ctx context.Context) (Session, error)
	GetLastSessionByWorkingDir(ctx context.Context, workingDir string) (Session, error)
	GetMCPOAuthClient(ctx context.Context, serverName string) (McpOauthClient, error)
	GetMCPOAuthToken(ctx context.Context, serverName string) (McpOauthToken, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetMessageChildren(ctx context.Context, parentID sql.NullString) ([]Message, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	ListAllSessions(ctx context.Context) ([]Session, error)
	ListFilesBySession(ctx context.Context, sessionID string) ([]File, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	ListPinnedSessions(ctx context.Context) ([]Session, error)
	ListSessionFilesByPath(ctx context.Context, arg ListSessionFilesByPathParams) ([]File, error)
	ListSessionReadFiles(ctx context.Context, sessionID string) ([]ReadFile, error)
	ListSessionsByWorkingDir(ctx context.Context, workingDir string) ([]Session, error)
	ListUserMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	ListUserMessagesByWorkingDir(ctx context.Context, workingDir string) ([]Message, error)
	RecordFileRead(ctx context.Context, arg RecordFileReadParams) error
	RenameSession(ctx context.Context, arg RenameSessionParams) error
	SetSessionPin(ctx context.Context, arg SetSessionPinParams) error
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateSessionLeaf(ctx context.Context, arg UpdateSessionLeafParams) error
	UpdateSessionTitleAndUsage(ctx context.Context, arg UpdateSessionTitleAndUsageParams) error
	UpsertMCPOAuthClient(ctx context.Context, arg UpsertMCPOAuthClientParams) error
	UpsertMCPOAuthToken(ctx context.Context, arg UpsertMCPOAuthTokenParams) error
}

var _ Querier = (*Queries)(nil)
