// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: step_usage.sql

package db

import (
	"context"
	"database/sql"
)

const deleteStepUsageBefore = `-- name: DeleteStepUsageBefore :exec
DELETE FROM step_usage WHERE response_finished_at < ?
`

func (q *Queries) DeleteStepUsageBefore(ctx context.Context, responseFinishedAt int64) error {
	_, err := q.exec(ctx, q.deleteStepUsageBeforeStmt, deleteStepUsageBefore, responseFinishedAt)
	return err
}

const insertStepUsage = `-- name: InsertStepUsage :exec
INSERT INTO step_usage (
    id, session_id, parent_session_id, working_dir, message_id, agent, kind,
    depth, run_id, step_index, attempt, provider, provider_type, model,
    request_started_at, response_finished_at, retry_count, finish_reason,
    input_tokens, cache_read_tokens, cache_write_tokens, output_tokens,
    reasoning_tokens, estimated, raw_usage,
    price_input, price_output, price_cache_read, price_cache_write, flat_rate,
    cache_policy, message_count, system_count, tool_count,
    tools_hash, system_hash, history_hash, history_prefix_match,
    fingerprint_error
) VALUES (
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?
)
`

type InsertStepUsageParams struct {
	ID                 string        `json:"id"`
	SessionID          string        `json:"session_id"`
	ParentSessionID    string        `json:"parent_session_id"`
	WorkingDir         string        `json:"working_dir"`
	MessageID          string        `json:"message_id"`
	Agent              string        `json:"agent"`
	Kind               string        `json:"kind"`
	Depth              int64         `json:"depth"`
	RunID              string        `json:"run_id"`
	StepIndex          int64         `json:"step_index"`
	Attempt            int64         `json:"attempt"`
	Provider           string        `json:"provider"`
	ProviderType       string        `json:"provider_type"`
	Model              string        `json:"model"`
	RequestStartedAt   int64         `json:"request_started_at"`
	ResponseFinishedAt int64         `json:"response_finished_at"`
	RetryCount         int64         `json:"retry_count"`
	FinishReason       string        `json:"finish_reason"`
	InputTokens        int64         `json:"input_tokens"`
	CacheReadTokens    int64         `json:"cache_read_tokens"`
	CacheWriteTokens   int64         `json:"cache_write_tokens"`
	OutputTokens       int64         `json:"output_tokens"`
	ReasoningTokens    int64         `json:"reasoning_tokens"`
	Estimated          int64         `json:"estimated"`
	RawUsage           string        `json:"raw_usage"`
	PriceInput         float64       `json:"price_input"`
	PriceOutput        float64       `json:"price_output"`
	PriceCacheRead     float64       `json:"price_cache_read"`
	PriceCacheWrite    float64       `json:"price_cache_write"`
	FlatRate           int64         `json:"flat_rate"`
	CachePolicy        string        `json:"cache_policy"`
	MessageCount       int64         `json:"message_count"`
	SystemCount        int64         `json:"system_count"`
	ToolCount          int64         `json:"tool_count"`
	ToolsHash          string        `json:"tools_hash"`
	SystemHash         string        `json:"system_hash"`
	HistoryHash        string        `json:"history_hash"`
	HistoryPrefixMatch sql.NullInt64 `json:"history_prefix_match"`
	FingerprintError   string        `json:"fingerprint_error"`
}

func (q *Queries) InsertStepUsage(ctx context.Context, arg InsertStepUsageParams) error {
	_, err := q.exec(ctx, q.insertStepUsageStmt, insertStepUsage,
		arg.ID,
		arg.SessionID,
		arg.ParentSessionID,
		arg.WorkingDir,
		arg.MessageID,
		arg.Agent,
		arg.Kind,
		arg.Depth,
		arg.RunID,
		arg.StepIndex,
		arg.Attempt,
		arg.Provider,
		arg.ProviderType,
		arg.Model,
		arg.RequestStartedAt,
		arg.ResponseFinishedAt,
		arg.RetryCount,
		arg.FinishReason,
		arg.InputTokens,
		arg.CacheReadTokens,
		arg.CacheWriteTokens,
		arg.OutputTokens,
		arg.ReasoningTokens,
		arg.Estimated,
		arg.RawUsage,
		arg.PriceInput,
		arg.PriceOutput,
		arg.PriceCacheRead,
		arg.PriceCacheWrite,
		arg.FlatRate,
		arg.CachePolicy,
		arg.MessageCount,
		arg.SystemCount,
		arg.ToolCount,
		arg.ToolsHash,
		arg.SystemHash,
		arg.HistoryHash,
		arg.HistoryPrefixMatch,
		arg.FingerprintError,
	)
	return err
}
